Document: checkmem
Title: Debian checkmem Manual
Author: <insert document author here>
Abstract: This manual describes what checkmem is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/checkmem/checkmem.sgml.gz

Format: postscript
Files: /usr/share/doc/checkmem/checkmem.ps.gz

Format: text
Files: /usr/share/doc/checkmem/checkmem.text.gz

Format: HTML
Index: /usr/share/doc/checkmem/html/index.html
Files: /usr/share/doc/checkmem/html/*.html
